### ISSUE TITLE
Ebean Enhancement should be enabled by default.

### ISSUE THREAD

**Issue by kreiger** [ebean-orm-tools/ebean-idea-enhancer#1]
I just saw you released the new plugin under the old name, and with a settings page!
Great!

Unfortunately, after upgrading, "Ebean Enhancement" was disabled.

I would expect it to be still enabled after upgrading.

I would go so far as to say it should probably be enabled by default when installed, to reduce confusion.

Presumably the user installed the plugin to use it, and hopes for it to work out of the box.

**Comment by rbygrave** [comment]
> Unfortunately, after upgrading, "Ebean Enhancement" was disabled.

Yes but I did state that when I released it and why that was the case on the group forum.  This plugin changed where the state was stored but I deemed that to be worth it (better storage option).

So yup, people need to turn it on.

**Comment by kreiger** [comment]
All right, i didn't notice any such statements when i upgraded in the Plugin Settings in IntelliJ.
I just pressed the "Update" button under "Available Updates".

Maybe at least make it enabled by default?

Users would hope for it to work out of the box after installing.

**Comment by rbygrave** [comment]
> Maybe at least make it enabled by default

So I'm still pondering that.  It is turned on per-project ... and many people are going to have quite a few projects that won't have Ebean at all so we don't really want to turn it on for those projects etc.  I'm not sure how to detect "installing with current project" vs "new project".

Do you  know how the plugin could detect that?

**Comment by kreiger** [comment]
That's a good point, i'm not sure.

**Comment by rbygrave** [comment]
So I'm thinking we should close this for now.  I think the "turn it on per-project" is working ok and maybe that is because the documentation with the plugin is a LOT more explicit about that now.

Re-open if you think we should look at this more.  
Thanks.
