### ISSUE TITLE
Support for Java 17

### ISSUE THREAD

**Issue by CollinAlpert** [ebean-orm-tools/ebean-idea-enhancer#6]
It seems when using Java 17, the plugin stops working. On Java 16 everything works fine, but as soon as I switch to Java 17 I get the familiar `io.ebean.config.BeanNotEnhancedException: Bean class models.Person is not enhanced?` exception.

Does support need to be added? I'd be happy to contribute a PR as soon as I get pointed into the right direction.

**Comment by rbygrave** [comment]
Reference to fix: 
https://github.com/ebean-orm/ebean-agent/pull/162


FYI: 
I have released ebean-agent version 12.9.1 with the fix. The updated IntelliJ plugin is awaiting approval, in the meantime we should be able to get the new plugin via:
 
https://plugins.jetbrains.com/plugin/10082-ebean-enhancer/versions/stable/121327
